# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalStartDateSchedule',
            fields=[
                ('intervalschedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.IntervalSchedule')),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'interval',
                'verbose_name_plural': 'intervals',
                'ordering': ['period', 'every'],
            },
            bases=('django_celery_beat.intervalschedule',),
        ),
        migrations.CreateModel(
            name='SolarSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('sunset', 'sunset'), ('dusk_civil', 'dusk_civil'), ('dusk_nautical', 'dusk_nautical'), ('solar_noon', 'solar_noon'), ('sunrise', 'sunrise'), ('dawn_civil', 'dawn_civil'), ('dusk_astronomical', 'dusk_astronomical'), ('dawn_nautical', 'dawn_nautical'), ('dawn_astronomical', 'dawn_astronomical')], max_length=24, verbose_name='event')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'solar event',
                'verbose_name_plural': 'solar events',
                'ordering': ('event', 'latitude', 'longitude'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='solarschedule',
            unique_together=set([('event', 'latitude', 'longitude')]),
        ),
        migrations.AddField(
            model_name='periodictask',
            name='solar',
            field=models.ForeignKey(blank=True, help_text='Use a solar schedule', null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.SolarSchedule', verbose_name='solar'),
        ),
    ]
